### ISSUE TITLE
Deployed bucket cannot be removed from S3

### ISSUE THREAD

**Issue by conanzxn** [fernando-mc/serverless-finch#60] opened 2018-06-21 10:50 UTC
This is a:

* Bug report

---

For bug reports:

### Expected behavior
The deployed bucket is expected to be removed successfully.

### Actual behavior
The bucket cannot be deleted as the following error outputs.
`ServerlessError: The bucket you tried to delete is not empty`

### Steps to reproduce
`sls client deploy` then `sls client remove`

* **Operating system:** Ubuntu 18.04
* **serverless-finch version:** 3.5.2
* `serverless.yml` **that produces bug:**
```
service: my-bucket-test

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs6.10
  region: eu-west-2
  environment:
    LOGGING_LEVEL: DEBUG

  # Give the service full access to the configured notified bucket
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::my-bucket-test/*"
package:
  exclude:
    - ./**
  include:
    - ./dist/**

plugins:
  - serverless-finch

custom:
  client:
    bucketName: my-bucket-test
    distributionFolder: ./dist
```

* **Command that produces bug:** `sls client remove`
* **Other details:**
```
Serverless Error ---------------------------------------
 
  ServerlessError: The bucket you tried to delete is not empty
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.27.2
```

**Comment by fernando-mc** [comment] 2018-06-23 02:22
@conanzxn Thanks for bringing this up - I'll take a look. Can you do me a favor and check the bucket itself and let me know if it looks empty or not?

Also can you let me know if you have versioning setup on the bucket? Just trying to think of a few things that could be wrong so I can try them out when I'm debugging this eventually.

**Comment by fernando-mc** [comment] 2018-06-26 00:01
@conanzxn I need a teeeeny bit more info here just to save me some time trying to debug this. Any chance you can add some answers to the above?

**Comment by conanzxn** [comment] 2018-06-26 09:39
@fernando-mc Sorry for the late reply. There is no versioning setup on the bucket. The bucket is created by finch deployment from scratch. Once the bucket is created, I can neither empty the bucket or delete the bucket from the S3 web UI. I have to delete the bucket forcefully via AWS CLI.

Hope it helps!

**Comment by fernando-mc** [comment] 2018-06-27 05:00
@conanzxn Thanks for the context here! I'll do some testing and see if I can recreate it this weekend!

**Comment by fernando-mc** [comment] 2018-06-30 22:17
@conanzxn I can't recreate this myself. I'm able to delete the bucket. Can you do me one more favor and check if the bucket has a policy on it? After reading some more AWS documentation it appears like that might cause this error too. 

Basically if you can't delete the bucket in the AWS UI while serverless finch _might_ have gotten the bucket into that state ultimately it's AWS that's not letting you delete it right?

**Comment by fernando-mc** [comment] 2018-07-10 15:18
Unfortunately, I was unable to reproduce this while testing and need a bit more information in order to try to find a fix for this or associate it with Serverless Finch. 

@conanzxn Please free to reopen after you have a chance to check the bucket's policy!

**Closed by fernando-mc** 2018-07-10 15:18 UTC
Labels: question

**Comment by lionheart2013** [comment] 2020-09-23 18:49
@fernando-mc , I am receiving this weird error "Could not find '/service-name/build' folder in your project root". This happens on github CICD setup. Deleting a branch should trigger a cleanup process unfortunately I am getting the error above. Weird thing is, these commands: sls deploy and sls remove works on my local machine but failed on CICD setup.
