### ISSUE TITLE
TypeError: (intermediate value).run is not a function

### ISSUE THREAD

**Issue by johnzoet** [fernando-mc/serverless-finch#135] opened 2022-01-18 20:52 UTC
This is a:

* [] Bug report

---

For bug reports:

### Expected behavior
Serverless client is deployed

### Actual behavior
Command "serverless client deploy" throws error:
TypeError: (intermediate value).run is not a function

### Steps to reproduce

Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              16.13.0
     Framework Version:         2.71.0 (standalone)
     Plugin Version:            5.5.3
     SDK Version:               4.3.0
     Components Version:        3.18.1

* `serverless.yml` **that produces bug:**
# serverless.yml
# cccouncilpublicwebsite.tk

service: publicwebsite
app: cccouncil
#org: srvlessfwrk
org: johnzoet

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: ap-southeast-2

package:
  exclude:
    - node_modules/**
    - backend/frontend/**
    - backend/venv/**
    - backend/.vscode/**
    - backend/__pycache__/**
    - backend/.dynamodb/**
    - ops/**    
    - .serverless/**
    - package-lock.json
    - .DS_Store

custom:
  client:
    #bucketName: cccouncilpublicwebsite.tk
    bucketName: cccouncilpublicwebsite.aws.zoetebier.net
    distributionFolder: frontend
    indexDocument: index.html
    errorDocument: error.html

plugins:
  - serverless-finch

* **Command that produces bug:**
 Command "serverless client deploy"

* **Other details:**

I encountered this bug while working as beta tester on a Manning liveProject "From On-Prem to AWS".
In the mean time I have created a fork of the main repository: 
This branch is up to date with fernando-mc:master.
I will submit a fix for this bug.

---

**Comment by martinhalford** [comment] 2022-02-15 03:15
@fernando-mc - Is this a legitimate bug in Serverless-finch, or should we be looking elsewhere?  Many thanks.

**Comment by fernando-mc** [comment] 2022-02-20 04:34
@johnzoet @martinhalford apologies for the delay. I haven't been able to look at this. 

If you're interested in helping with #142 please comment there and I'd be happy to get in touch and talk it over! It might be a legitimate bug or an issue that cropped up in new versions of the framework.

**Comment by mikejpeters** [comment] 2022-02-26 18:59
Duplicate of #132

**Closed by mikejpeters** 2022-02-26 18:59 UTC
