### ISSUE TITLE
TypeError: (intermediate value).run is not a function

### ISSUE THREAD

**Issue by arman-teahorse** [fernando-mc/serverless-finch#132] opened 2021-12-22 18:54 UTC
This is a:

* Feature request or change
* [x] Bug report

---

For bug reports:

### Expected behavior
Frontend is deployed to AWS when running 'serverless client deploy'.

### Actual behavior
Frontend is not deployed, with the following error:
Serverless: Configuration warning at 'functions.api.events[0].http': value 'ANY {proxy+}' does not satisfy pattern /^(?:\*|(GET|POST|PUT|PATCH|OPTIONS|HEAD|DELETE|ANY) (\/\S*))$/i
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: This deployment will:
Serverless: - Upload all files from 'public' to bucket 'bucketName' undefined
Serverless: - Set (and overwrite) bucket 'bucketName' configuration
Serverless: - Set (and overwrite) bucket 'bucketName' bucket policy
Serverless: - Set (and overwrite) bucket 'bucketName' CORS policy
 
 Serverless Error ----------------------------------------
 
  TypeError: (intermediate value).run is not a function
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.18.2
     Framework Version:         2.69.1 (local)
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1
 
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221".
            While it is highly encouraged to upgrade to new algorithm, you can still use the old approach by setting "provider.lambdaHashingVersion" to "20200924".
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2

### Steps to reproduce

* **Operating system:** See above (Mac OS 11.6.1)
* **serverless-finch version:** 2.8.0 (as defined in package.json file)
* `serverless.yml` **that produces bug:**

service: serviceName

provider:
 name: aws
 runtime: nodejs14.x
 memorySize: 2048
 timeout: 60
 stage: prod
 region: us-east-2

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /

plugins:
  - serverless-finch

custom:
  client:
    bucketName: bucketName
    distributionFolder: folderName
    # [other configuration parameters]

* **Command that produces bug:**

'serverless client deploy' (or in my case: 'npm run deployfrontend')

* **Other details:**

npm (global?) version: 6.14.15
npm (local?) version: 8.3.0 (as defined in package.json file)

I scanned my prior commits and noticed I was previously running npm local version 7.24.2 and serverless-finch 2.6.0. When I rolled back to these versions, **the bug went away**.

I'm running serverless version 2.64.1.

No idea if this is actually a bug, or just a version compatibility issue. Either way, any insight would be greatly appreciated. Thank you.

---

**Comment by JacksonGariety** [comment] 2021-12-27 03:40
I am also experiencing this issue

**Comment by jaredchu** [comment] 2021-12-30 11:26
The issue is in confirm code, currently we can avoid it using `--no-confirm` option:
```
serverless client deploy --no-confirm
```

**Comment by arman-teahorse** [comment] 2021-12-30 18:20
Thanks for sharing. Next time I run this code I will try that out.

**Comment by hardzeichyksiarhei** [comment] 2022-01-21 14:19
> The issue is in confirm code, currently we can avoid it using `--no-confirm` option:
> 
> ```
> serverless client deploy --no-confirm
> ```
Thanks! :)

**Comment by fernando-mc** [comment] 2022-02-20 04:36
Apologies for the delay on this! Would you be interested in helping with #142? Unfortunately I am no longer able to maintain this plugin and am looking to find folks who can help with it.

**Comment by Shereef** [comment] 2022-02-26 19:12
I think this would be fixed with the merge of #144 can you please test it out @arman-teahorse

**Comment by Shereef** [comment] 2022-02-26 22:17
@johnzoet tested this and it has been resolved

Please open another issue if you have any more concerns

**Closed** 2022-02-26 22:17 UTC
Labels: bug
